/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCurrentRound200,
  GetRoundHistoryParams,
  PagedRoundDto,
  RoundVerifyDto
} from '.././schemas';

import { fetchClient } from '../../mutator/fetch-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Return the round currently open for bets or in flight, or null between rounds.
 */
export const getGetCurrentRoundUrl = () => {


  

  return `/games/rounds/current`
}

export const getCurrentRound = async ( options?: RequestInit): Promise<GetCurrentRound200> => {
  
  return fetchClient<GetCurrentRound200>(getGetCurrentRoundUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCurrentRoundQueryKey = () => {
    return [
    `/games/rounds/current`
    ] as const;
    }

    
export const getGetCurrentRoundQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentRound>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentRound>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentRoundQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentRound>>> = ({ signal }) => getCurrentRound({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentRound>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentRoundQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentRound>>>
export type GetCurrentRoundQueryError = unknown


export function useGetCurrentRound<TData = Awaited<ReturnType<typeof getCurrentRound>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentRound>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentRound>>,
          TError,
          Awaited<ReturnType<typeof getCurrentRound>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentRound<TData = Awaited<ReturnType<typeof getCurrentRound>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentRound>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentRound>>,
          TError,
          Awaited<ReturnType<typeof getCurrentRound>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentRound<TData = Awaited<ReturnType<typeof getCurrentRound>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentRound>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return the round currently open for bets or in flight, or null between rounds.
 */

export function useGetCurrentRound<TData = Awaited<ReturnType<typeof getCurrentRound>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentRound>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentRoundQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Paginated history of crashed rounds.
 */
export const getGetRoundHistoryUrl = (params?: GetRoundHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/games/rounds/history?${stringifiedParams}` : `/games/rounds/history`
}

export const getRoundHistory = async (params?: GetRoundHistoryParams, options?: RequestInit): Promise<PagedRoundDto> => {
  
  return fetchClient<PagedRoundDto>(getGetRoundHistoryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetRoundHistoryQueryKey = (params?: GetRoundHistoryParams,) => {
    return [
    `/games/rounds/history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRoundHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getRoundHistory>>, TError = unknown>(params?: GetRoundHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoundHistory>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRoundHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoundHistory>>> = ({ signal }) => getRoundHistory(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoundHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoundHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getRoundHistory>>>
export type GetRoundHistoryQueryError = unknown


export function useGetRoundHistory<TData = Awaited<ReturnType<typeof getRoundHistory>>, TError = unknown>(
 params: undefined |  GetRoundHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoundHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoundHistory>>,
          TError,
          Awaited<ReturnType<typeof getRoundHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoundHistory<TData = Awaited<ReturnType<typeof getRoundHistory>>, TError = unknown>(
 params?: GetRoundHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoundHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoundHistory>>,
          TError,
          Awaited<ReturnType<typeof getRoundHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoundHistory<TData = Awaited<ReturnType<typeof getRoundHistory>>, TError = unknown>(
 params?: GetRoundHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoundHistory>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Paginated history of crashed rounds.
 */

export function useGetRoundHistory<TData = Awaited<ReturnType<typeof getRoundHistory>>, TError = unknown>(
 params?: GetRoundHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoundHistory>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRoundHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Reveal the provably-fair verification payload.
 */
export const getVerifyRoundUrl = (roundId: string,) => {


  

  return `/games/rounds/${roundId}/verify`
}

export const verifyRound = async (roundId: string, options?: RequestInit): Promise<RoundVerifyDto> => {
  
  return fetchClient<RoundVerifyDto>(getVerifyRoundUrl(roundId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getVerifyRoundQueryKey = (roundId?: string,) => {
    return [
    `/games/rounds/${roundId}/verify`
    ] as const;
    }

    
export const getVerifyRoundQueryOptions = <TData = Awaited<ReturnType<typeof verifyRound>>, TError = void>(roundId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyRound>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVerifyRoundQueryKey(roundId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyRound>>> = ({ signal }) => verifyRound(roundId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(roundId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyRound>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VerifyRoundQueryResult = NonNullable<Awaited<ReturnType<typeof verifyRound>>>
export type VerifyRoundQueryError = void


export function useVerifyRound<TData = Awaited<ReturnType<typeof verifyRound>>, TError = void>(
 roundId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyRound>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyRound>>,
          TError,
          Awaited<ReturnType<typeof verifyRound>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyRound<TData = Awaited<ReturnType<typeof verifyRound>>, TError = void>(
 roundId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyRound>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyRound>>,
          TError,
          Awaited<ReturnType<typeof verifyRound>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerifyRound<TData = Awaited<ReturnType<typeof verifyRound>>, TError = void>(
 roundId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyRound>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Reveal the provably-fair verification payload.
 */

export function useVerifyRound<TData = Awaited<ReturnType<typeof verifyRound>>, TError = void>(
 roundId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyRound>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifyRoundQueryOptions(roundId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




