/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wallets Service
 * Player wallet management API for Crash Game.
 * OpenAPI spec version: 0.1.0
 */

export * from './healthCheckResponseDto';
export * from './walletDto';