/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wallets Service
 * Player wallet management API for Crash Game.
 * OpenAPI spec version: 0.1.0
 */

export interface WalletDto {
  /** Wallet identifier. */
  id: string;
  /** Owner player id (matches JWT sub claim). */
  playerId: string;
  /** Balance in integer cents as a string to preserve BigInt precision. */
  balance: string;
  createdAt?: string;
}
