/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BetDto,
  GetMyBetsParams,
  PagedBetDto,
  PlaceBetDto
} from '.././schemas';

import { fetchClient } from '../../mutator/fetch-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List bets placed by the authenticated player.
 */
export const getGetMyBetsUrl = (params?: GetMyBetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/games/bets/me?${stringifiedParams}` : `/games/bets/me`
}

export const getMyBets = async (params?: GetMyBetsParams, options?: RequestInit): Promise<PagedBetDto> => {
  
  return fetchClient<PagedBetDto>(getGetMyBetsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyBetsQueryKey = (params?: GetMyBetsParams,) => {
    return [
    `/games/bets/me`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMyBetsQueryOptions = <TData = Awaited<ReturnType<typeof getMyBets>>, TError = unknown>(params?: GetMyBetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBets>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyBetsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBets>>> = ({ signal }) => getMyBets(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyBets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyBetsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyBets>>>
export type GetMyBetsQueryError = unknown


export function useGetMyBets<TData = Awaited<ReturnType<typeof getMyBets>>, TError = unknown>(
 params: undefined |  GetMyBetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBets>>,
          TError,
          Awaited<ReturnType<typeof getMyBets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyBets<TData = Awaited<ReturnType<typeof getMyBets>>, TError = unknown>(
 params?: GetMyBetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyBets>>,
          TError,
          Awaited<ReturnType<typeof getMyBets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyBets<TData = Awaited<ReturnType<typeof getMyBets>>, TError = unknown>(
 params?: GetMyBetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBets>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List bets placed by the authenticated player.
 */

export function useGetMyBets<TData = Awaited<ReturnType<typeof getMyBets>>, TError = unknown>(
 params?: GetMyBetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyBets>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyBetsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Place a bet on the current round.
 */
export const getPlaceBetUrl = () => {


  

  return `/games/bet`
}

export const placeBet = async (placeBetDto: PlaceBetDto, options?: RequestInit): Promise<BetDto> => {
  
  return fetchClient<BetDto>(getPlaceBetUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      placeBetDto,)
  }
);}




export const getPlaceBetMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeBet>>, TError,{data: PlaceBetDto}, TContext>, request?: SecondParameter<typeof fetchClient>}
): UseMutationOptions<Awaited<ReturnType<typeof placeBet>>, TError,{data: PlaceBetDto}, TContext> => {

const mutationKey = ['placeBet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof placeBet>>, {data: PlaceBetDto}> = (props) => {
          const {data} = props ?? {};

          return  placeBet(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlaceBetMutationResult = NonNullable<Awaited<ReturnType<typeof placeBet>>>
    export type PlaceBetMutationBody = PlaceBetDto
    export type PlaceBetMutationError = void

    /**
 * @summary Place a bet on the current round.
 */
export const usePlaceBet = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeBet>>, TError,{data: PlaceBetDto}, TContext>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof placeBet>>,
        TError,
        {data: PlaceBetDto},
        TContext
      > => {

      const mutationOptions = getPlaceBetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Cash out the current bet at the live multiplier.
 */
export const getCashOutUrl = () => {


  

  return `/games/bet/cashout`
}

export const cashOut = async ( options?: RequestInit): Promise<BetDto> => {
  
  return fetchClient<BetDto>(getCashOutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getCashOutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cashOut>>, TError,void, TContext>, request?: SecondParameter<typeof fetchClient>}
): UseMutationOptions<Awaited<ReturnType<typeof cashOut>>, TError,void, TContext> => {

const mutationKey = ['cashOut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cashOut>>, void> = () => {
          

          return  cashOut(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CashOutMutationResult = NonNullable<Awaited<ReturnType<typeof cashOut>>>
    
    export type CashOutMutationError = void

    /**
 * @summary Cash out the current bet at the live multiplier.
 */
export const useCashOut = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cashOut>>, TError,void, TContext>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cashOut>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCashOutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    