/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { fetchClient } from '../../mutator/fetch-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getPrometheusControllerIndexUrl = () => {


  

  return `/games/metrics`
}

export const prometheusControllerIndex = async ( options?: RequestInit): Promise<void> => {
  
  return fetchClient<void>(getPrometheusControllerIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getPrometheusControllerIndexQueryKey = () => {
    return [
    `/games/metrics`
    ] as const;
    }

    
export const getPrometheusControllerIndexQueryOptions = <TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrometheusControllerIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof prometheusControllerIndex>>> = ({ signal }) => prometheusControllerIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrometheusControllerIndexQueryResult = NonNullable<Awaited<ReturnType<typeof prometheusControllerIndex>>>
export type PrometheusControllerIndexQueryError = unknown


export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof prometheusControllerIndex>>,
          TError,
          Awaited<ReturnType<typeof prometheusControllerIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof prometheusControllerIndex>>,
          TError,
          Awaited<ReturnType<typeof prometheusControllerIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePrometheusControllerIndex<TData = Awaited<ReturnType<typeof prometheusControllerIndex>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof prometheusControllerIndex>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrometheusControllerIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




