/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wallets Service
 * Player wallet management API for Crash Game.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  WalletDto
} from '.././schemas';

import { fetchClient } from '../../mutator/fetch-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Return the authenticated player wallet (auto-provisioned on first read).
 */
export const getGetMyWalletUrl = () => {


  

  return `/wallets/me`
}

export const getMyWallet = async ( options?: RequestInit): Promise<WalletDto> => {
  
  return fetchClient<WalletDto>(getGetMyWalletUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyWalletQueryKey = () => {
    return [
    `/wallets/me`
    ] as const;
    }

    
export const getGetMyWalletQueryOptions = <TData = Awaited<ReturnType<typeof getMyWallet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWallet>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyWalletQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyWallet>>> = ({ signal }) => getMyWallet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyWallet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyWalletQueryResult = NonNullable<Awaited<ReturnType<typeof getMyWallet>>>
export type GetMyWalletQueryError = unknown


export function useGetMyWallet<TData = Awaited<ReturnType<typeof getMyWallet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWallet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyWallet>>,
          TError,
          Awaited<ReturnType<typeof getMyWallet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyWallet<TData = Awaited<ReturnType<typeof getMyWallet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWallet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyWallet>>,
          TError,
          Awaited<ReturnType<typeof getMyWallet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyWallet<TData = Awaited<ReturnType<typeof getMyWallet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWallet>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return the authenticated player wallet (auto-provisioned on first read).
 */

export function useGetMyWallet<TData = Awaited<ReturnType<typeof getMyWallet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWallet>>, TError, TData>>, request?: SecondParameter<typeof fetchClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyWalletQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




