/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import type { BetStatus } from './betStatus';

export interface BetDto {
  id: string;
  /** Owner user id (matches JWT sub claim). */
  userId: string;
  username: string;
  /** Bet amount in integer cents as a string. */
  amountCents: string;
  status: BetStatus;
  /**
   * Cashout multiplier in integer hundredths (150 = 1.50x).
   * @nullable
   */
  cashoutMultiplierHundredths: number | null;
  /**
   * Payout in integer cents as a string. null until settled.
   * @nullable
   */
  payoutCents: string | null;
  createdAt: string;
}
