/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */

export type BetStatus = typeof BetStatus[keyof typeof BetStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BetStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  WON: 'WON',
  LOST: 'LOST',
} as const;
