/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import type { RoundDto } from './roundDto';

export type GetCurrentRound200 = RoundDto | null;
