/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import type { LeaderboardWindow } from './leaderboardWindow';

export type GetLeaderboardParams = {
window?: LeaderboardWindow;
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
