/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */

export interface LeaderboardEntryDto {
  /** Owner user id. */
  userId: string;
  username: string;
  /** Gross winnings in integer cents as a string. */
  winningsCents: string;
  /** Number of bets contributing to the row. */
  betsCount: number;
  /** Biggest multiplier hit in integer hundredths (250 = 2.50x). */
  biggestMultiplierHundredths: number;
}
