/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */

export type LeaderboardWindow = typeof LeaderboardWindow[keyof typeof LeaderboardWindow];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeaderboardWindow = {
  '24h': '24h',
  '7d': '7d',
} as const;
