/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import type { LeaderboardWindow } from './leaderboardWindow';
import type { LeaderboardEntryDto } from './leaderboardEntryDto';

export interface LeaderboardResponseDto {
  window: LeaderboardWindow;
  entries: LeaderboardEntryDto[];
  /** Generation timestamp; used as a freshness cue by the UI. */
  generatedAt: string;
}
