/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import type { BetDto } from './betDto';

export interface PagedBetDto {
  /** @minimum 1 */
  page: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize: number;
  /** @minimum 0 */
  total: number;
  items: BetDto[];
}
