/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */

export interface PlaceBetDto {
  /** Bet amount in integer cents, e.g. "1000" for R$ 10.00. */
  amount: string;
}
