/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */
import type { RoundStatus } from './roundStatus';
import type { BetDto } from './betDto';

export interface RoundDto {
  id: string;
  /** Monotonic round counter. */
  nonce: number;
  status: RoundStatus;
  /** SHA-256 commitment of the server seed. */
  hashCommitment: string;
  /** Pre-published client seed mixed into the crash-point HMAC. */
  clientSeed: string;
  bettingEndsAt: string;
  /** @nullable */
  flyingStartedAt: string | null;
  /** @nullable */
  crashedAt: string | null;
  /** Exponential growth rate k for m(t) = exp(k * Δt). */
  growthRate: number;
  /**
   * Crash point in integer hundredths. Null until CRASHED.
   * @nullable
   */
  crashPointHundredths: number | null;
  /**
   * Revealed server seed. Null until the round CRASHED.
   * @nullable
   */
  serverSeed: string | null;
  bets: BetDto[];
  /** Server timestamp captured when this payload was generated. Used by the frontend to align multiplier projections. */
  serverTime: string;
}
