/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */

export type RoundStatus = typeof RoundStatus[keyof typeof RoundStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoundStatus = {
  BETTING_PHASE: 'BETTING_PHASE',
  FLYING: 'FLYING',
  CRASHED: 'CRASHED',
} as const;
