/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Games Service
 * Crash Game engine API: rounds, bets, provably fair.
 * OpenAPI spec version: 0.1.0
 */

export interface RoundVerifyDto {
  roundId: string;
  nonce: number;
  /** Revealed server seed. */
  serverSeed: string;
  clientSeed: string;
  hashCommitment: string;
  /** Crash point in integer hundredths. */
  crashPointHundredths: number;
}
