/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PlayRouteImport } from './routes/play'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as VerifyRoundIdRouteImport } from './routes/verify.$roundId'
import { Route as PlaygroundWalletRouteImport } from './routes/playground/wallet'
import { Route as PlaygroundVerifyRouteImport } from './routes/playground/verify'
import { Route as PlaygroundRoundRouteImport } from './routes/playground/round'
import { Route as PlaygroundHistoryRouteImport } from './routes/playground/history'
import { Route as PlaygroundBetRouteImport } from './routes/playground/bet'
import { Route as PlaygroundAuthRouteImport } from './routes/playground/auth'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundRoute,
} as any)
const VerifyRoundIdRoute = VerifyRoundIdRouteImport.update({
  id: '/verify/$roundId',
  path: '/verify/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundWalletRoute = PlaygroundWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundVerifyRoute = PlaygroundVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundRoundRoute = PlaygroundRoundRouteImport.update({
  id: '/round',
  path: '/round',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundHistoryRoute = PlaygroundHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundBetRoute = PlaygroundBetRouteImport.update({
  id: '/bet',
  path: '/bet',
  getParentRoute: () => PlaygroundRoute,
} as any)
const PlaygroundAuthRoute = PlaygroundAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PlaygroundRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/play': typeof PlayRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/playground/auth': typeof PlaygroundAuthRoute
  '/playground/bet': typeof PlaygroundBetRoute
  '/playground/history': typeof PlaygroundHistoryRoute
  '/playground/round': typeof PlaygroundRoundRoute
  '/playground/verify': typeof PlaygroundVerifyRoute
  '/playground/wallet': typeof PlaygroundWalletRoute
  '/verify/$roundId': typeof VerifyRoundIdRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/play': typeof PlayRoute
  '/playground/auth': typeof PlaygroundAuthRoute
  '/playground/bet': typeof PlaygroundBetRoute
  '/playground/history': typeof PlaygroundHistoryRoute
  '/playground/round': typeof PlaygroundRoundRoute
  '/playground/verify': typeof PlaygroundVerifyRoute
  '/playground/wallet': typeof PlaygroundWalletRoute
  '/verify/$roundId': typeof VerifyRoundIdRoute
  '/playground': typeof PlaygroundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/play': typeof PlayRoute
  '/playground': typeof PlaygroundRouteWithChildren
  '/playground/auth': typeof PlaygroundAuthRoute
  '/playground/bet': typeof PlaygroundBetRoute
  '/playground/history': typeof PlaygroundHistoryRoute
  '/playground/round': typeof PlaygroundRoundRoute
  '/playground/verify': typeof PlaygroundVerifyRoute
  '/playground/wallet': typeof PlaygroundWalletRoute
  '/verify/$roundId': typeof VerifyRoundIdRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/me'
    | '/play'
    | '/playground'
    | '/playground/auth'
    | '/playground/bet'
    | '/playground/history'
    | '/playground/round'
    | '/playground/verify'
    | '/playground/wallet'
    | '/verify/$roundId'
    | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/me'
    | '/play'
    | '/playground/auth'
    | '/playground/bet'
    | '/playground/history'
    | '/playground/round'
    | '/playground/verify'
    | '/playground/wallet'
    | '/verify/$roundId'
    | '/playground'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/me'
    | '/play'
    | '/playground'
    | '/playground/auth'
    | '/playground/bet'
    | '/playground/history'
    | '/playground/round'
    | '/playground/verify'
    | '/playground/wallet'
    | '/verify/$roundId'
    | '/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PlayRoute: typeof PlayRoute
  PlaygroundRoute: typeof PlaygroundRouteWithChildren
  VerifyRoundIdRoute: typeof VerifyRoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/verify/$roundId': {
      id: '/verify/$roundId'
      path: '/verify/$roundId'
      fullPath: '/verify/$roundId'
      preLoaderRoute: typeof VerifyRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/wallet': {
      id: '/playground/wallet'
      path: '/wallet'
      fullPath: '/playground/wallet'
      preLoaderRoute: typeof PlaygroundWalletRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/verify': {
      id: '/playground/verify'
      path: '/verify'
      fullPath: '/playground/verify'
      preLoaderRoute: typeof PlaygroundVerifyRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/round': {
      id: '/playground/round'
      path: '/round'
      fullPath: '/playground/round'
      preLoaderRoute: typeof PlaygroundRoundRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/history': {
      id: '/playground/history'
      path: '/history'
      fullPath: '/playground/history'
      preLoaderRoute: typeof PlaygroundHistoryRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/bet': {
      id: '/playground/bet'
      path: '/bet'
      fullPath: '/playground/bet'
      preLoaderRoute: typeof PlaygroundBetRouteImport
      parentRoute: typeof PlaygroundRoute
    }
    '/playground/auth': {
      id: '/playground/auth'
      path: '/auth'
      fullPath: '/playground/auth'
      preLoaderRoute: typeof PlaygroundAuthRouteImport
      parentRoute: typeof PlaygroundRoute
    }
  }
}

interface PlaygroundRouteChildren {
  PlaygroundAuthRoute: typeof PlaygroundAuthRoute
  PlaygroundBetRoute: typeof PlaygroundBetRoute
  PlaygroundHistoryRoute: typeof PlaygroundHistoryRoute
  PlaygroundRoundRoute: typeof PlaygroundRoundRoute
  PlaygroundVerifyRoute: typeof PlaygroundVerifyRoute
  PlaygroundWalletRoute: typeof PlaygroundWalletRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

const PlaygroundRouteChildren: PlaygroundRouteChildren = {
  PlaygroundAuthRoute: PlaygroundAuthRoute,
  PlaygroundBetRoute: PlaygroundBetRoute,
  PlaygroundHistoryRoute: PlaygroundHistoryRoute,
  PlaygroundRoundRoute: PlaygroundRoundRoute,
  PlaygroundVerifyRoute: PlaygroundVerifyRoute,
  PlaygroundWalletRoute: PlaygroundWalletRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}

const PlaygroundRouteWithChildren = PlaygroundRoute._addFileChildren(
  PlaygroundRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PlayRoute: PlayRoute,
  PlaygroundRoute: PlaygroundRouteWithChildren,
  VerifyRoundIdRoute: VerifyRoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
